export const categories = [
  { id: 1, name: "appliances" },
  { id: 2, name: "automotive" },
  { id: 3, name: "baby" },
  { id: 4, name: "beauty" },
  { id: 5, name: "books" },
  { id: 6, name: "clothing" },
  { id: 7, name: "computers" },
  { id: 8, name: "electronics" },
  { id: 9, name: "entertainment" },
  { id: 10, name: "food" },
  { id: 11, name: "furniture" },
  { id: 12, name: "games" },
  { id: 13, name: "health" },
  { id: 14, name: "home" },
  { id: 15, name: "jewelry" },
  { id: 16, name: "music" },
  { id: 17, name: "office" },
  { id: 18, name: "outdoors" },
  { id: 19, name: "pets" },
  { id: 20, name: "sports" },
  { id: 21, name: "tools" },
  { id: 22, name: "toys" },
  { id: 23, name: "travel" },
  { id: 24, name: "vehicles" },
  { id: 25, name: "art" },
  { id: 26, name: "crafts" },
  { id: 27, name: "photography" },
  { id: 28, name: "gardening" },
  { id: 29, name: "beverages" },
  { id: 30, name: "cooking" },
  { id: 31, name: "baking" },
  { id: 32, name: "cleaning" },
  { id: 33, name: "maintenance" },
  { id: 34, name: "fitness" },
  { id: 35, name: "wellness" },
  { id: 36, name: "yoga" },
  { id: 37, name: "meditation" },
  { id: 38, name: "mindfulness" },
  { id: 39, name: "games" },
  { id: 40, name: "puzzles" },
  { id: 41, name: "board games" },
  { id: 42, name: "card games" },
  { id: 43, name: "video games" },
  { id: 44, name: "VR games" },
  { id: 45, name: "console games" },
  { id: 46, name: "mobile games" },
  { id: 47, name: "tablet games" },
  { id: 48, name: "computer games" },
  { id: 49, name: "playstation games" },
  { id: 50, name: "xbox games" },
  { id: 51, name: "nintendo games" },
  { id: 52, name: "classic games" },
  { id: 53, name: "retro games" },
  { id: 54, name: "old-school games" },
  { id: 55, name: "vintage games" },
  { id: 56, name: "antique games" },
  { id: 57, name: "collectible games" },
  { id: 58, name: "rare games" },
  { id: 59, name: "limited edition games" },
  { id: 60, name: "exclusive games" },
  { id: 61, name: "custom games" },
  { id: 62, name: "handmade games" },
  { id: 63, name: "personalized games" },
  { id: 64, name: "bespoke games" },
  { id: 65, name: "artisan games" },
  { id: 66, name: "unique games" },
  { id: 67, name: "uncommon games" },
  { id: 68, name: "extraordinary games" },
  { id: 69, name: "special games" },
  { id: 70, name: "rare games" },
  { id: 71, name: "limited edition games" },
  { id: 72, name: "exclusive games" },
  { id: 73, name: "collectible games" },
  { id: 74, name: "vintage games" },
  { id: 75, name: "classic games" },
  { id: 76, name: "retro games" },
  { id: 77, name: "old-school games" },
  { id: 78, name: "board games" },
  { id: 79, name: "card games" },
  { id: 80, name: "strategy games" },
  { id: 81, name: "role-playing games" },
  { id: 82, name: "simulation games" },
  { id: 83, name: "puzzle games" },
  { id: 84, name: "educational games" },
  { id: 85, name: "action games" },
  { id: 86, name: "adventure games" },
  { id: 87, name: "multiplayer games" },
  { id: 88, name: "single-player games" },
  { id: 89, name: "online games" },
  { id: 90, name: "offline games" },
  { id: 91, name: "mobile games" },
  { id: 92, name: "console games" },
  { id: 93, name: "PC games" },
  { id: 94, name: "tablet games" },
  { id: 95, name: "VR games" },
  { id: 96, name: "AR games" },
  { id: 97, name: "board games" },
  { id: 98, name: "card games" },
  { id: 99, name: "role-playing games" },
  { id: 100, name: "video games" },
];

import { PrismaClient } from "@prisma/client";

const prismaClient = new PrismaClient();
async function main() {
  setTimeout(() => {
    categories.forEach(async ({ name }) => {
      await prismaClient.category.create({
        data: {
          name,
        },
      });
    });
  }, 2000);
}
main()
  .catch((e) => {
    console.log(e);
  })
  .finally(() => {
    prismaClient.$disconnect();
  });
