import { type AppType } from "next/app";
import { Inter } from "next/font/google";
import { DiscountDiv, Navbar } from "@/components";
import { api } from "@/utils/api";
import "@/styles/globals.css";
import Head from "next/head";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});
const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`font-sans ${inter.variable} relative min-h-screen w-screen`}
      >
        <div className="h-[100%] w-screen bg-white">
          <Navbar />
          <DiscountDiv />
          <Component {...pageProps} />
        </div>
        <Toaster position="top-right" reverseOrder={false} />
      </main>
    </>
  );
};

export default api.withTRPC(MyApp);
